from homeassistant.components.select import SelectEntity
from custom_components.vialitoral.api import Api

import logging

_LOGGER = logging.getLogger(__name__)

async def async_setup_entry(hass, config_entry, async_add_entities):
    api = Api()
    
    async_add_entities([ VialitoralSelect(await api.get_cameras()) ])

class VialitoralSelect(SelectEntity):

    def __init__(self, options):
        super().__init__()
        
        data = [ ' '.join(cam['name'].split(' ')[2:]) for cam in options ]

        self._current = data[0]
        self._options = data
        
    @property
    def unique_id(self):
        return "vialitoral_vialitoral_autogenerated"
        
    @property
    def name(self):
        return "vialitoral_autogenerated"
        
    @property
    def current_option(self):
        return self._current

    @property
    def options(self):
        return self._options

    @property
    def icon(self):
        return "mdi:cctv"

    @property
    def state_attributes(self):
        attrs = {"total": len(self._options)}

        return attrs

    async def async_select_option(self, option: str) -> None:
        self._current = option