"""Camera platform for the Vialitoral integration.

Exposes each Vialitoral highway CCTV as a HA Camera entity. Images are
fetched on a per-camera staggered schedule to avoid hitting the remote
server with a burst of simultaneous requests. Each camera waits a random
delay (0–30 s) before its first fetch, then refreshes every SCAN_INTERVAL.

Also provides a VialitoralActiveCamera entity (camera.vialitoral_active)
that always serves the image of whichever camera is currently selected in
the select entity, with no additional API calls.
"""
from homeassistant.components.camera import Camera
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.event import async_track_time_interval, async_call_later
from homeassistant.core import callback
from . import DOMAIN, CONF_CAMERAS

import logging
import base64
import random
from datetime import timedelta

_LOGGER = logging.getLogger(__name__)

# How often each camera refreshes after its initial staggered fetch.
SCAN_INTERVAL = timedelta(seconds=60)

# Maximum random delay (seconds) before a camera's first fetch.
# Spreads N cameras evenly across this window at startup.
_MAX_STAGGER_SECONDS = 30

# Entity ID of the select that drives the active camera.
_SELECT_ENTITY_ID = "select.vialitoral_autogenerated"

# 1×1 transparent GIF used as a placeholder before the first successful fetch.
_BLANK_GIF = base64.b64decode(
    'R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
)


async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up Vialitoral camera entities from a config entry."""
    api = hass.data[DOMAIN][config_entry.entry_id]

    selected_ids = set(config_entry.data.get(CONF_CAMERAS, []))
    all_cameras = await api.get_cameras()
    filtered = [cam for cam in all_cameras if str(cam["image"]) in selected_ids] if selected_ids else all_cameras

    cameras = [VialitoralCamera(cam, api) for cam in filtered]

    # Store a label→instance map so VialitoralActiveCamera can look up
    # cached images without making additional API calls.
    hass.data[DOMAIN][config_entry.entry_id + "_cam_map"] = {
        cam._name: cam for cam in cameras
    }

    active_camera = VialitoralActiveCamera(config_entry.entry_id)

    # Store the proxy camera instance so the select entity can push updates
    # directly instead of relying on state-change event subscription.
    hass.data[DOMAIN][config_entry.entry_id + "_active_cam"] = active_camera

    # update_before_add is intentionally False — each camera self-staggers
    # its first fetch via async_added_to_hass to avoid a request burst.
    async_add_entities(cameras + [active_camera], update_before_add=False)


class VialitoralCamera(Camera):
    """Representation of a single Vialitoral CCTV camera."""

    def __init__(self, data, api):
        """Initialise the camera entity from raw API data.

        Args:
            data: Camera dict from the Vialitoral API (name, image, latitude,
                  longitude, type).
            api:  Shared Api instance injected from hass.data.
        """
        super().__init__()

        self._distance = data['name'].split(' ')[1]
        self._name = " ".join(data['name'].split(' ')[2:])
        self._id = data['image']
        self._latitude = data['latitude']
        self._longitude = data['longitude']
        self._type = data['type']
        self._detection = 0

        self._api = api
        self._image = _BLANK_GIF
        self._unsub_interval = None

        # Each camera picks a unique random delay so fetches are spread out.
        self._stagger_delay = random.uniform(0, _MAX_STAGGER_SECONDS)

    async def async_added_to_hass(self):
        """Schedule the first fetch after a random stagger delay, then set up
        a fixed periodic interval for subsequent refreshes."""
        await super().async_added_to_hass()

        async def _initial_update(_now=None):
            await self._fetch_and_write()
            self._unsub_interval = async_track_time_interval(
                self.hass, self._handle_interval, SCAN_INTERVAL
            )

        async_call_later(self.hass, self._stagger_delay, _initial_update)
        _LOGGER.debug(
            "Camera %s will start fetching in %.1f s",
            self._name,
            self._stagger_delay,
        )

    async def async_will_remove_from_hass(self):
        """Cancel the periodic interval when the entity is removed."""
        if self._unsub_interval:
            self._unsub_interval()
            self._unsub_interval = None

    @callback
    def _handle_interval(self, now):
        """Fire-and-forget wrapper called by the time interval tracker."""
        self.hass.async_create_task(self._fetch_and_write())

    async def _fetch_and_write(self):
        """Fetch a new image and push the updated state to HA."""
        await self.async_update()
        self.async_write_ha_state()

    async def async_update(self):
        """Fetch a fresh snapshot from the Vialitoral API.

        On failure the previous image is retained and a warning is logged.
        """
        _LOGGER.info("Refreshing %s image", self._name)
        try:
            encoded = await self._api.get_camera_image(
                ("" if self._type == "vialitoral" else "_" + self._type),
                str(self._id),
            )
            self._image = base64.decodebytes(encoded)
        except Exception as e:
            _LOGGER.warning("Failed to update camera %s: %s", self._name, e, exc_info=True)

    async def async_camera_image(self, width=None, height=None):
        """Return the most recently fetched camera image bytes."""
        return self._image

    @property
    def should_poll(self):
        """Disable HA polling — this entity manages its own schedule."""
        return False

    @property
    def unique_id(self):
        """Return a unique ID for this camera entity."""
        return f"vialitoral_{self._type}_{self._id}"

    @property
    def name(self):
        """Return the camera display name."""
        return self._name

    @property
    def icon(self):
        """Return the icon for this camera."""
        return "mdi:cctv"

    @property
    def device_info(self):
        """Group all cameras under a single 'Vialitoral CCTV' device."""
        return DeviceInfo(
            identifiers={(DOMAIN, "vialitoral_cctv")},
            name="Vialitoral CCTV",
            manufacturer=self._type,
            model="webcam",
        )

    @property
    def extra_state_attributes(self):
        """Return additional state attributes exposed to the HA frontend."""
        return {
            "latitude": self._latitude,
            "longitude": self._longitude,
            "type": self._type,
            "id": self._id,
            "distance": self._distance,
            "objects": self._detection,
        }


class VialitoralActiveCamera(Camera):
    """Proxy camera that always shows the currently selected camera.

    Serves the cached image of whichever VialitoralCamera is chosen in
    select.vialitoral_autogenerated. No additional API calls are made —
    it reads the image already held in memory by the selected camera entity.
    Use 'camera.vialitoral_active' in Lovelace cards for dynamic selection:

        type: picture-entity
        entity: camera.vialitoral_active
    """

    # Prevent HA from prefixing the entity_id with the device name.
    @property
    def has_entity_name(self):
        """Return False so HA uses the entity name directly as the entity ID."""
        return False

    def __init__(self, entry_id: str):
        """Initialise the active camera proxy."""
        super().__init__()
        self._entry_id = entry_id
        self._image = _BLANK_GIF
        self._selected_label: str | None = None

    async def async_added_to_hass(self):
        """Perform an initial lookup once HA has fully started."""
        await super().async_added_to_hass()

    def update_selection(self, label: str) -> None:
        """Called directly by the select entity when the user picks a camera."""
        cam_map = self.hass.data[DOMAIN].get(self._entry_id + "_cam_map", {})
        cam = cam_map.get(label)

        if cam is None:
            _LOGGER.warning("Active camera: no camera found for label '%s'", label)
            return

        self._image = cam._image
        self._selected_label = label
        self.async_write_ha_state()

    async def async_camera_image(self, width=None, height=None):
        """Return the image of the currently selected camera."""
        # Live lookup so the image is current on first render.
        select_state = self.hass.states.get(_SELECT_ENTITY_ID)
        if select_state:
            cam_map = self.hass.data[DOMAIN].get(self._entry_id + "_cam_map", {})
            cam = cam_map.get(select_state.state)
            if cam is not None:
                self._image = cam._image

        return self._image

    @property
    def extra_state_attributes(self):
        """Expose the selected label so state_changed fires on each selection."""
        return {"active_camera": self._selected_label}

    @property
    def should_poll(self):
        """Disable polling — updates are pushed directly from the select entity."""
        return False

    @property
    def device_info(self):
        """Group the active camera under the same Vialitoral CCTV device."""
        return DeviceInfo(
            identifiers={(DOMAIN, "vialitoral_cctv")},
            name="Vialitoral CCTV",
            model="webcam",
        )

    @property
    def unique_id(self):
        """Return a unique ID for the active camera entity."""
        return "vialitoral_active_camera"

    @property
    def name(self):
        """Return the entity display name."""
        return "Vialitoral Active"

    @property
    def icon(self):
        """Return the icon."""
        return "mdi:cctv"
