"""Select platform for the Vialitoral integration.

Provides a single SelectEntity whose options are the display names of all
Vialitoral cameras. Selecting an option exposes the corresponding camera's
HA entity ID and raw API ID via extra_state_attributes so Lovelace cards and
automations can dynamically point to the chosen camera.

Example Lovelace usage:
    type: picture-entity
    entity: "{{ state_attr('select.vialitoral_autogenerated', 'selected_entity_id') }}"
"""
from homeassistant.components.select import SelectEntity
from . import DOMAIN

import logging

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up the Vialitoral select entity from a config entry."""
    api = hass.data[DOMAIN][config_entry.entry_id]

    async_add_entities([VialitoralSelect(await api.get_cameras())])


def _camera_label(cam: dict) -> str:
    """Human-readable label for a camera (everything after the km marker)."""
    return " ".join(cam["name"].split(" ")[2:])


def _camera_entity_id(cam: dict) -> str:
    """Derive the HA entity_id for a camera entity from its label.

    Note: assumes simple ASCII names. Accented or special characters may
    cause the derived slug to differ from HA's actual slugification.
    Use 'selected_camera_id' as a reliable fallback in that case.
    """
    label = _camera_label(cam)
    slug = label.lower().replace(" ", "_")
    return f"camera.{slug}"


class VialitoralSelect(SelectEntity):
    """Select entity that exposes all Vialitoral cameras as choosable options."""

    def __init__(self, cameras: list):
        """Initialise the select entity.

        Args:
            cameras: Full camera list returned by Api.get_cameras().
        """
        super().__init__()

        # Map display label → raw camera data for fast lookups
        self._map: dict[str, dict] = {_camera_label(cam): cam for cam in cameras}
        self._options: list[str] = list(self._map.keys())
        self._current: str = self._options[0]

    @property
    def unique_id(self):
        """Return a unique ID for this select entity."""
        return "vialitoral_vialitoral_autogenerated"

    @property
    def name(self):
        """Return the entity display name."""
        return "vialitoral_autogenerated"

    @property
    def current_option(self):
        """Return the currently selected camera label."""
        return self._current

    @property
    def options(self):
        """Return the list of all available camera labels."""
        return self._options

    @property
    def icon(self):
        """Return the icon for this select entity."""
        return "mdi:cctv"

    @property
    def extra_state_attributes(self):
        """Return extra attributes for the currently selected camera.

        Attributes:
            total:               Total number of available cameras.
            selected_camera_id:  Raw API numeric ID of the selected camera.
            selected_entity_id:  Derived HA entity ID (e.g. camera.some_spot).
            selected_latitude:   GPS latitude of the selected camera.
            selected_longitude:  GPS longitude of the selected camera.
        """
        cam = self._map.get(self._current, {})
        return {
            "total": len(self._options),
            "selected_camera_id": cam.get("image"),
            "selected_entity_id": _camera_entity_id(cam) if cam else None,
            "selected_latitude": cam.get("latitude"),
            "selected_longitude": cam.get("longitude"),
        }

    async def async_select_option(self, option: str) -> None:
        """Handle a new option being selected.

        Ignores unknown options to prevent state corruption.
        """
        if option in self._map:
            self._current = option
            self.async_write_ha_state()