"""Select platform for the Vialitoral integration.

Provides a single SelectEntity whose options are the display names of all
Vialitoral cameras. Selecting an option updates camera.vialitoral_active
(the proxy camera entity) which Lovelace cards can point to statically:

    type: picture-entity
    entity: camera.vialitoral_active
"""
from homeassistant.components.select import SelectEntity
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.util import slugify
from . import DOMAIN

import logging

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up the Vialitoral select entity from a config entry."""
    api = hass.data[DOMAIN][config_entry.entry_id]

    async_add_entities([VialitoralSelect(config_entry.entry_id, await api.get_cameras())])


def _camera_label(cam: dict) -> str:
    """Human-readable label for a camera (everything after the km marker)."""
    return " ".join(cam["name"].split(" ")[2:])


def _camera_entity_id(cam: dict) -> str:
    """Derive the HA entity_id for a camera entity from its label.

    Uses HA's own slugify utility so accented characters (á→a, à→a, ó→o,
    í→i, ç→c, etc.) are normalised identically to how HA names the camera
    entities themselves.
    """
    return f"camera.{slugify(_camera_label(cam))}"


class VialitoralSelect(SelectEntity):
    """Select entity that exposes all Vialitoral cameras as choosable options."""

    def __init__(self, entry_id: str, cameras: list):
        """Initialise the select entity.

        Args:
            entry_id: Config entry ID used to reach the proxy camera in hass.data.
            cameras:  Full camera list returned by Api.get_cameras().
        """
        super().__init__()

        self._entry_id = entry_id
        # Map display label → raw camera data for fast lookups
        self._map: dict[str, dict] = {_camera_label(cam): cam for cam in cameras}
        self._options: list[str] = list(self._map.keys())
        self._current: str = self._options[0]

    @property
    def unique_id(self):
        """Return a unique ID for this select entity."""
        return "vialitoral_vialitoral_autogenerated"

    @property
    def device_info(self):
        """Group the select entity under the Vialitoral CCTV device."""
        return DeviceInfo(
            identifiers={(DOMAIN, "vialitoral_cctv")},
            name="Vialitoral CCTV",
            model="webcam",
        )

    @property
    def name(self):
        """Return the entity display name."""
        return "vialitoral_autogenerated"

    @property
    def current_option(self):
        """Return the currently selected camera label."""
        return self._current

    @property
    def options(self):
        """Return the list of all available camera labels."""
        return self._options

    @property
    def icon(self):
        """Return the icon for this select entity."""
        return "mdi:cctv"

    @property
    def extra_state_attributes(self):
        """Return extra attributes for the currently selected camera.

        Attributes:
            total:               Total number of available cameras.
            selected_camera_id:  Raw API numeric ID of the selected camera.
            selected_entity_id:  Derived HA entity ID (e.g. camera.some_spot).
            selected_latitude:   GPS latitude of the selected camera.
            selected_longitude:  GPS longitude of the selected camera.
        """
        cam = self._map.get(self._current, {})
        return {
            "total": len(self._options),
            "selected_camera_id": cam.get("image"),
            "selected_entity_id": _camera_entity_id(cam) if cam else None,
            "selected_latitude": cam.get("latitude"),
            "selected_longitude": cam.get("longitude"),
        }

    async def async_select_option(self, option: str) -> None:
        """Handle a new option being selected.

        Updates own state, then directly pushes the new image to the proxy
        camera entity so the frontend refreshes immediately.
        """
        if option not in self._map:
            return

        self._current = option
        self.async_write_ha_state()

        active_cam = self.hass.data[DOMAIN].get(self._entry_id + "_active_cam")
        if active_cam is not None:
            active_cam.update_selection(option)