"""Select platform for the Vialitoral integration.

Provides a single SelectEntity whose options are the display names of all
Vialitoral cameras. Selecting an option updates camera.vialitoral_active
(the proxy camera entity) which Lovelace cards can point to statically:

    type: picture-entity
    entity: camera.vialitoral_active
"""
from __future__ import annotations

import logging

from homeassistant.components.select import SelectEntity
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.util import slugify

from .const import DOMAIN, camera_label
from .coordinator import VialitoralCoordinator

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the Vialitoral select entity from a config entry."""
    coordinator: VialitoralCoordinator = hass.data[DOMAIN][config_entry.entry_id]

    async_add_entities([VialitoralSelect(coordinator)])


def _camera_entity_id(cam: dict) -> str:
    """Derive the HA entity_id for a camera entity from its label.

    Uses HA's own slugify utility so accented characters (á→a, à→a, ó→o,
    í→i, ç→c, etc.) are normalised identically to how HA names the camera
    entities themselves.
    """
    return f"camera.{slugify(camera_label(cam))}"


class VialitoralSelect(SelectEntity):
    """Select entity that exposes all Vialitoral cameras as choosable options."""

    _attr_has_entity_name = False
    _attr_icon = "mdi:cctv"
    _attr_name = "Active camera"
    _attr_unique_id = "vialitoral_vialitoral_autogenerated"

    def __init__(self, coordinator: VialitoralCoordinator):
        """Initialise the select entity.

        Args:
            coordinator: Shared coordinator holding the camera list and the
                currently selected camera id.
        """
        super().__init__()

        self._coordinator = coordinator
        # Map display label → raw camera data for fast lookups.
        self._map: dict[str, dict] = {
            camera_label(cam): cam for cam in coordinator.cameras
        }
        self._attr_options = list(self._map.keys())

        # Align the initial option with the coordinator's selected camera.
        self._current = self._attr_options[0] if self._attr_options else None
        for label, cam in self._map.items():
            if str(cam["image"]) == coordinator.selected_camera_id:
                self._current = label
                break

    @property
    def device_info(self):
        """Group the select entity under the Vialitoral CCTV device."""
        return DeviceInfo(
            identifiers={(DOMAIN, "vialitoral_cctv")},
            name="Vialitoral CCTV",
            model="webcam",
        )

    @property
    def current_option(self):
        """Return the currently selected camera label."""
        return self._current

    @property
    def extra_state_attributes(self):
        """Return extra attributes for the currently selected camera.

        Attributes:
            total:               Total number of available cameras.
            selected_camera_id:  Raw API numeric ID of the selected camera.
            selected_entity_id:  Derived HA entity ID (e.g. camera.some_spot).
            selected_latitude:   GPS latitude of the selected camera.
            selected_longitude:  GPS longitude of the selected camera.
        """
        cam = self._map.get(self._current, {})
        return {
            "total": len(self._attr_options),
            "selected_camera_id": cam.get("image"),
            "selected_entity_id": _camera_entity_id(cam) if cam else None,
            "selected_latitude": cam.get("latitude"),
            "selected_longitude": cam.get("longitude"),
        }

    async def async_select_option(self, option: str) -> None:
        """Handle a new option being selected.

        Updates own state and the coordinator's selected camera id, then asks
        the coordinator to notify its entities so camera.vialitoral_active
        refreshes immediately.
        """
        cam = self._map.get(option)
        if cam is None:
            return

        self._current = option
        self._coordinator.selected_camera_id = str(cam["image"])
        self.async_write_ha_state()
        self._coordinator.async_update_listeners()